version: "3.8"

# 10 Things to Consider When Planning Your Elasticsearch Project: https://ecmarchitect.com/archives/2015/07/27/4031
# Using Apache JMeter to Test Elasticsearch: https://ecmarchitect.com/archives/2014/09/02/3915

services:
  viz:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    deploy:
        placement: 
            constraints: [node.role == manager]

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:latest
    hostname: swarm-listener
    networks:
      - elastic
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy:
    image: dockerflow/docker-flow-proxy:latest
    hostname: proxy
    ports:
      - "80:80"
      - "443:443"
      - "9200:9200"
      - "8200:8200"
    networks:
      - elastic
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=9200,8200
    deploy:                                                                            
      placement:                                                                       
        constraints: [node.role == manager]

  redis:
    image: redis:5.0.3
    command:
      - "redis-server"
      - "--cluster-enabled yes"
      - "--cluster-config-file nodes.conf"
      - "--cluster-node-timeout 5000"
      - "--appendonly yes"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - elastic
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.7.0}
    environment:
      # https://github.com/docker/swarmkit/issues/1951
      - node.name={{.Node.Hostname}}
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=worker1
      #- node.master=true 
      - discovery.zen.ping.unicast.hosts=elasticsearch
      - cluster.name=es_cluster
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
      - xpack.security.enabled=true
      - xpack.monitoring.collection.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.license.self_generated.type=trial
      - network.host=0.0.0.0
    networks:
      - elastic
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    deploy:
      endpoint_mode: dnsrr
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=9200
        - com.df.srcPort=9200
      placement: 
        constraints: [node.labels.region==elasticsearch]

  logstashA:                                                                       
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-7.7.0}           
    hostname: "{{.Node.Hostname}}-logstash"                                        
    environment:                                                                   
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200               
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic} 
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    ports:                                                                         
      - "12201:12201/udp"                                                          
    networks:                                                                      
      - elastic                                                                    
    configs:                                                                       
      - source: lsa_config                                                         
        target: /usr/share/logstash/pipeline/logstashA.conf

  logstashB:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-7.7.0}
    hostname: "{{.Node.Hostname}}-logstash"
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME:-elastic}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-changeme}
    ports:
      - "12202:12202/udp"
    networks:
      - elastic
    configs:
      - source: lsb_config
        target: /usr/share/logstash/pipeline/1logstashB.conf
   
networks:
   elastic:
      external: true

volumes:
  elasticsearch:
  log_example:

configs:
  lsa_config:
    file: $PWD/elk/logstash/config/pipeline/logstashA.conf
  lsb_config:
    file: $PWD/elk/logstash/config/pipeline/logstashB.conf